# Generated by Django 4.1.1 on 2023-05-23 23:57

from django.db import migrations
import csv


def get_dolar_records(apps, schema_editor):
    Dolar = apps.get_model("dolar", "Dolar")

    with open('dolar_data.csv', 'r') as file:
        reader = csv.reader(file)
        Dolar.objects.bulk_create(
            [Dolar(name=row[0], description=row[1]) for row in reader]
        )


class Migration(migrations.Migration):
    dependencies = [
        ('dolar', '0001_initial'),
    ]

    operations = [migrations.RunPython(get_dolar_records)]
