version: "3.9"

services:
  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - redis
  redis:
    image: redis
  celery:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - django
    command: celery -A dolar_app worker --beat --loglevel=info